<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\KeyTracker.Core\KeyTracker.Core.csproj" />
    <ProjectReference Include="..\KeyTracker.Infrastructure\KeyTracker.Infrastructure.csproj" />
    <ProjectReference Include="..\KeyTracker.Migrations\KeyTracker.Migrations.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
